### ISSUE TITLE
DataFetcherDefinition.isAsyncFetcher 永远为false

### ISSUE THREAD

**Issue by wsamuel** [graphql-calculator/graphql-calculator#96]
` public DataFetcherDefinition build() {
            return new DataFetcherDefinition(
                    isAsyncFetcher, isGraphqlAsyncFetcher, isCalculatorAsyncFetcher,
                    originalFetcher, wrappedDataFetcher, actionFetcher, executor
            );
 }`

calculator.common.GraphQLUtil#getDataFetcherDefinition
该方法并为对isAsyncFetcher赋值，所以一直为false

**Comment by dugenkui03** [comment]
Fix in https://github.com/graphql-calculator/graphql-calculator/commit/358d1ae74626974585e2a90797f64cc7b61d3b35
